version: "3.7"

x-common-variables: &common-variables
  # these variables need to be defined in an .env file
  RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
  RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
  TIX_API_HOST: $TIX_API_HOST
  TIX_API_PORT: $TIX_API_PORT
  TIX_API_USER: $TIX_API_ADMIN_USERNAME
  # TIX_API_SSL: True # uncomment to enable SSL
  TIX_API_PASSWORD: $TIX_API_ADMIN_PASSWORD

volumes:
  ReportsVolume:
  SchedulerVolume:
  iptoas-datadir:
  mysql-datadir:
  sql-dump:

x-common-logging: &common-logging
  options:
    max-size: 200m

services:
  tix-time-server:
    restart: always
    image: tixmeasurements/tix-time-server:latest
    # build:
    #   context: ../tix-time-server
    environment:
      <<: *common-variables
      TIX__QUEUE__HOST: rabbitmq
      TIX__QUEUE__USER: $RABBITMQ_USERNAME
      TIX__QUEUE__PASSWORD: $RABBITMQ_PASSWORD
      TIX__LOG_LEVEL: ALL
      TIX__LOG-LEVEL: ALL
    ports:
      - "4500:4500/udp"
      - "8080:8080/tcp"
    depends_on:
      - rabbitmq
    logging:
      <<: *common-logging

  tix-client-trigger:
    restart: always
    image: tixmeasurements/client-trigger:latest
    # build:
    #   context: tix-client-trigger
    environment:
      PORT: 7561
    ports:
      - "7561:7561/udp"
    logging:
      <<: *common-logging

  tix-time-condenser:
    restart: always
    image: tixmeasurements/tix-time-condenser:latest
    # build:
    #   context: ../tix-time-condenser
    volumes:
      - ReportsVolume:/tmp/reports
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: $RABBITMQ_USERNAME 
      SPRING_RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD
      TIX_CONDENSER_TIX_API_HTTPS: $TIX_API_HTTPS
      TIX_CONDENSER_TIX_API_HOST: $TIX_API_HOST
      TIX_CONDENSER_TIX_API_PORT: $TIX_API_PORT
      TIX_CONDENSER_TIX_API_USER: $TIX_API_ADMIN_USERNAME
      TIX_CONDENSER_TIX_API_PASSWORD: $TIX_API_ADMIN_PASSWORD
    logging:
      <<: *common-logging

  tix-time-processor-beat:
    restart: always
    image: "tixmeasurements/tix-time-processor:latest"
    # build:
    #   context: ../tix-time-processor
    environment:
      <<: *common-variables
      PROCESSOR_TYPE: BEAT
      TIX_REPORTS_BASE_PATH: /reports
      TIX_RABBITMQ_USER: $RABBITMQ_USERNAME
      TIX_RABBITMQ_PASS: $RABBITMQ_PASSWORD
      TIX_RABBITMQ_HOST: rabbitmq
    volumes:
      - SchedulerVolume:/tmp/celerybeat-schedule.d
    depends_on:
      - rabbitmq
    logging:
      <<: *common-logging

  tix-time-processor-worker:
    restart: always
    image: "tixmeasurements/tix-time-processor:latest"
    # build:
    #   context: ../tix-time-processor
    environment:
      <<: *common-variables
      PROCESSOR_TYPE: WORKER
      TIX_REPORTS_BASE_PATH: /reports
      TIX_RABBITMQ_USER: $RABBITMQ_USERNAME
      TIX_RABBITMQ_PASS: $RABBITMQ_PASSWORD
      TIX_RABBITMQ_HOST: rabbitmq
    volumes:
      - ReportsVolume:/reports
      - SchedulerVolume:/tmp/celerybeat-schedule.d
    depends_on:
      - rabbitmq
    logging:
      <<: *common-logging

  tix-api:
    restart: always
    image: tixmeasurements/tix-api:latest
    # build:
    #   context: ../tix-api
    command: "./wait-for-it.sh --host=mysql --port=3306 --timeout=30 -- npm start"
    ports:
      - "3001:3001/tcp"
    depends_on:
      - mysql
    environment:
      <<: *common-variables
      RECAPTCHA_SECRET_KEY: $RECAPTCHA_SECRET_KEY
    logging:
      <<: *common-logging

  tix-iptoas:
    image: tixmeasurements/iptoas:latest
    # build:
    #   context: ../ip_to_as
    command: "echo 'this service is manually executed'"
    depends_on:
      - mysql
    volumes:
      # store downloaded files in the host machine so they can be manually
      # deleted if desired
      - ./iptoas_downloads:/app/downloads
    logging:
      <<: *common-logging

  tix-web:
    restart: always
    image: tixmeasurements/tix-web:latest
    # build:
    #   context: ../tix-web
    ports:
      - "$WEB_PORT:80"
    logging:
      <<: *common-logging
  
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    environment:
      <<: *common-variables
    ports:
      - "15672:15672"
    logging:
      <<: *common-logging

  mysql:
    restart: always
    image: mysql/mysql-server:5.7.28
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: tix
      MYSQL_DATABASE: tix
      MYSQL_USER: tix
      MYSQL_PASSWORD: tix
    logging:
      <<: *common-logging
    # volumes:
    #   - mysql-datadir:/var/lib/mysql
    #   - sql-dump:/docker-entrypoint-initdb.d
